---
title: LeRobot.js
emoji: 🤖
colorFrom: purple
colorTo: pink
sdk: static
license: apache-2.0
build: "cd examples/cyberpunk-standalone && pnpm install && pnpm build"
app_file: examples/cyberpunk-standalone/dist/index.html
pinned: true
---

