---
title: LeRobot.js
emoji: 🤖
colorFrom: blue
colorTo: green
sdk: static
app_build_command: cd examples/cyberpunk-standalone && pnpm install && pnpm build
app_file: examples/cyberpunk-standalone/dist/index.html
pinned: true
---

